print("Veterinary Patient Calculator")
print("------------------------------")
name= input("Enter animal name:")
species=input("Enter species(Dog/Cat")
age=float(input("Enter age in years:"))
weight=float(input("Enter weight in kg:"))
temprature=float(input("Enter body temprature in C:"))
print()
print("Patient Information")
print("---------------------")
print("Name:",name)
print("Species:",species)
print("Age:",age,"years")
print("Weight:",weight,"kg")
print("Body Temprature:",temprature,"C")
